# Generated by Django 3.2.8 on 2022-02-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loveApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hermassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('love', models.CharField(max_length=300)),
                ('Condition', models.CharField(max_length=300)),
                ('massage', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='YourAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('herquestion', models.CharField(max_length=300)),
            ],
        ),
    ]
