# Generated by Django 3.2.8 on 2022-03-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loveApp', '0002_hermassage_youranswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mera_question_uska_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sort', models.CharField(default=1900, max_length=10)),
                ('Mera_Question', models.CharField(max_length=600)),
                ('Neha_ka_Jawab_of_specifice_question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Uska_question_mera_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(default=1900, max_length=10)),
                ('date', models.DateField()),
                ('Uska_specific_question', models.CharField(max_length=600)),
                ('MyAnswers', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='UskaMassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.CharField(default=1900, max_length=10)),
                ('date', models.DateField()),
                ('repeated_questions_ka_answer', models.CharField(max_length=300)),
                ('kaisi_ho_ka_answer', models.CharField(max_length=300)),
                ('Uska_massage', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='HerAnswer',
        ),
        migrations.DeleteModel(
            name='Hermassage',
        ),
        migrations.DeleteModel(
            name='YourAnswer',
        ),
    ]
