# Generated by Django 3.2.8 on 2022-03-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loveApp', '0003_auto_20220308_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mera_question_uska_answer',
            name='sort',
            field=models.CharField(default=1899, max_length=10),
        ),
        migrations.AlterField(
            model_name='uska_question_mera_answer',
            name='sort',
            field=models.IntegerField(default=1899, max_length=10),
        ),
        migrations.AlterField(
            model_name='uskamassage',
            name='sort',
            field=models.CharField(default=1899, max_length=10),
        ),
    ]
