# Generated by Django 3.2.8 on 2022-03-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loveApp', '0004_auto_20220309_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('I_am_there_sonu', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='mera_question_uska_answer',
            name='sort',
            field=models.CharField(default=1896, max_length=10),
        ),
        migrations.AlterField(
            model_name='uska_question_mera_answer',
            name='sort',
            field=models.IntegerField(default=1896, max_length=10),
        ),
        migrations.AlterField(
            model_name='uskamassage',
            name='sort',
            field=models.CharField(default=1896, max_length=10),
        ),
    ]
