# Generated by Django 3.2.8 on 2022-03-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loveApp', '0006_attendence_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='Time',
            field=models.CharField(default='and the time is 16 bazke : 19 minute : 43 second par aayi thi', max_length=50),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='name',
            field=models.CharField(default='I love Neha and days_left is1896', max_length=499),
        ),
    ]
