# Generated by Django 3.2.8 on 2022-03-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loveApp', '0007_auto_20220312_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mera_Jawwab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_left', models.CharField(default=1895, max_length=233)),
                ('MyAnswers', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Mera_sawwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_left', models.CharField(default=1895, max_length=233)),
                ('Mera_Specific_sawwal', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Uska_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_left', models.CharField(default=1895, max_length=10)),
                ('Neha_ka_Jawab_of_specifice_question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Uska_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Uska_specific_question', models.CharField(max_length=600)),
            ],
        ),
        migrations.DeleteModel(
            name='Mera_question_uska_answer',
        ),
        migrations.DeleteModel(
            name='Uska_question_mera_answer',
        ),
        migrations.AlterField(
            model_name='attendence',
            name='Time',
            field=models.CharField(default='19:39:07 not accurate', max_length=50),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='name',
            field=models.CharField(default='I love Neha and days_left is1895', max_length=499),
        ),
        migrations.AlterField(
            model_name='uskamassage',
            name='sort',
            field=models.CharField(default=1895, max_length=10),
        ),
    ]
