# Generated by Django 3.2.8 on 2022-03-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loveApp', '0008_auto_20220313_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='mera_jawwab',
            name='name',
            field=models.CharField(default='Mera Answers 1895', max_length=122),
        ),
        migrations.AddField(
            model_name='mera_sawwal',
            name='name',
            field=models.CharField(default='Sonu ka Sawwal 1895', max_length=122),
        ),
        migrations.AddField(
            model_name='uska_answer',
            name='name',
            field=models.CharField(default='Neha ka answer 1895', max_length=122),
        ),
        migrations.AddField(
            model_name='uska_question',
            name='name',
            field=models.CharField(default='Neha ka Question 1895', max_length=122),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='Time',
            field=models.CharField(default='19:52:54 not accurate', max_length=50),
        ),
    ]
