# Generated by Django 3.2.8 on 2022-03-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loveApp', '0010_auto_20220313_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='Time',
            field=models.CharField(default='20:10:30 not accurate', max_length=50),
        ),
        migrations.AlterField(
            model_name='mera_jawwab',
            name='MyAnswers',
            field=models.CharField(max_length=6000),
        ),
        migrations.AlterField(
            model_name='mera_jawwab',
            name='name',
            field=models.CharField(default='Mera Answers 1895', max_length=6000),
        ),
        migrations.AlterField(
            model_name='mera_sawwal',
            name='Mera_Specific_sawwal',
            field=models.CharField(max_length=6000),
        ),
        migrations.AlterField(
            model_name='mera_sawwal',
            name='name',
            field=models.CharField(default='Sonu ka Sawwal 1895', max_length=6000),
        ),
        migrations.AlterField(
            model_name='uska_answer',
            name='name',
            field=models.CharField(default='Neha ka answer 1895', max_length=6000),
        ),
        migrations.AlterField(
            model_name='uska_question',
            name='Uska_specific_question',
            field=models.CharField(max_length=6000),
        ),
        migrations.AlterField(
            model_name='uska_question',
            name='name',
            field=models.CharField(default='Neha ka Question 1895', max_length=6000),
        ),
    ]
