# Generated by Django 3.2.8 on 2022-03-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loveApp', '0013_alter_attendence_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uskamassage',
            name='date',
        ),
        migrations.AlterField(
            model_name='attendence',
            name='Time',
            field=models.CharField(default='22:43:16 not accurate', max_length=50),
        ),
    ]
