# Generated by Django 3.2.8 on 2022-03-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loveApp', '0015_auto_20220318_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updates',
            name='S_N',
        ),
        migrations.AlterField(
            model_name='attendence',
            name='Time',
            field=models.CharField(default='15:09:44 not accurate', max_length=50),
        ),
    ]
